version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      - SA_PASSWORD=Nh@td11y
      - ACCEPT_EULA=Y
    ports:
      - "1436:1433"
    volumes:
      - mssql_data:/var/opt/mssql/

volumes:
  mssql_data:
    driver_opts:
      device: ${mylocal}
      type: none
      o: bind
